### ISSUE TITLE
"latest" TAG on Docker is Commit  c182732, "nightly" is "f869bb1"

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#185]
Please give me a short hint, if the code is stable enough to make the next "latest" tag

**Comment by jlkalberer** [comment]
Nope -- definitely not stable. Probably some time next week.

Right now variables + functions aren't working. 

@AntonPuko - anything else? Also how long before you finish your refactor?

**Comment by AntonPuko** [comment]
1) variables are working 
2) functions aren't.

I'm currently fighting with deviceDescription(+ perf issue related with that) I hope I'll finish it in 1-2 days. But I can't guarantee that everything will be stable after the changes because attributes caching is a pretty big refactoring that affects most parts of functionality and probably there will be some iterations.

**Comment by AntonPuko** [comment]
* functions works after https://github.com/Brewskey/spark-protocol/commit/3159c667a816b9e14ea3dc5b9401563b6a171bdb

**Comment by haeferer** [comment]
Flashing is not working so "latest" will be unchanged

**Comment by haeferer** [comment]
nightly is now f869bb1, latest still unchanged
