### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by durielz** [Brewskey/spark-server#52]
You guys are doing a great job!

I was trying to build using `npm run build && node ./build/main.js` and i got this error:

`.../node_modules/spark-protocol/lib/server/DeviceServer_v2.js:485
var _ref5 = _asyncToGenerator(regeneratorRuntime.mark(function _callee6(eventName, data, deviceID) {
ReferenceError: regeneratorRuntime is not defined`

**Comment by AntonPuko** [comment]
Thanks, @durielz. We miss babel-transform-runtime-plugin in spark-protocol and spark-server. The issue will be fixed after merging these two:
https://github.com/Brewskey/spark-protocol/pull/13 and https://github.com/Brewskey/spark-server/pull/53
Also notice, in order to run build without exceptions atm,  you need to move oauthClients.json from `src` to `build` manually.

**Comment by jlkalberer** [comment]
@durielz - we will be cleaning this all up before we launch it for everybody.  Some of the things we are doing right now don't make consuming the library great -- they just make development faster.
