### ISSUE TITLE
ouath clients

### ISSUE THREAD

**Issue by AntonPuko** [Brewskey/spark-server#67]
now ouathClients are hard coded in .json
we need to realize that endpoint: https://docs.particle.io/reference/api/#create-an-oauth-client
so, one more repo/controller etc.

**Comment by durielz** [comment]
Are you guys going to implement also organizations, products and customers?

**Comment by jlkalberer** [comment]
I'm not sure about organizations/customers but I think we might add products.  I will probably need this feature eventually.

Do organizations and customers make sense for private cloud?  I don't think it's a lot of work to add these features now that everything has been refactored though.

**Comment by durielz** [comment]
I agree for products, they can help managing, flashing and triggering group of devices.

If you have more than one type of product, i think you could have to handle different user profile data so customers are the right way to do it implementing what Particle call two-legged authentication.
I did it in my private server in order to manage user registration/login from another server asking a customer token for claiming and accessing devices data.

But if you have only one product or some that shares user profile data, they don't make sense. Developers could extend the user creation endpoint saving their own data.
